version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/clojure:1.11.1
    steps:
      - checkout
      - run: lein cljfmt check
  test:
    docker:
      - image: cimg/clojure:1.11.1
    steps:
      - checkout
      - run: lein test

workflows:
  lint-test:
    jobs:
      - lint
      - test
